language: node_js
notifications:
  email: false
node_js:
  - '10.15.3'
before_install: npm install -g npm@6.2.0
script:
  - npm test && npm run codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
